<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorSeeder extends Seeder {
    public function run(): void {
        $now = now();
        DB::table('vendors')->insertOrIgnore([
            ['name'=>'Oracle Corporation',      'code'=>'VND001','category_id'=>1,'type'=>'service_provider','contact_name'=>'Account Manager',  'contact_email'=>'ae@oracle.com',           'country'=>'USA',          'account_manager_id'=>5,'status'=>'approved','risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2023-01-15','qualification_expiry'=>'2025-01-15','overall_rating'=>4.2,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'Al-Futtaim Tech Services','code'=>'VND002','category_id'=>1,'type'=>'service_provider','contact_name'=>'Saleh Al-Futtaim', 'contact_email'=>'saleh@alfuttaim-tech.ae',  'country'=>'UAE',          'account_manager_id'=>5,'status'=>'active', 'risk_level'=>'medium','qualification_status'=>'qualified','qualification_date'=>'2023-06-01','qualification_expiry'=>'2025-06-01','overall_rating'=>3.8,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'KPMG Saudi Arabia',       'code'=>'VND003','category_id'=>2,'type'=>'consultant',      'contact_name'=>'Partner Office',   'contact_email'=>'riyadh@kpmg.com.sa',       'country'=>'Saudi Arabia', 'account_manager_id'=>3,'status'=>'approved','risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2024-01-01','qualification_expiry'=>'2026-01-01','overall_rating'=>4.5,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'Jadawel Facilities Mgmt', 'code'=>'VND004','category_id'=>3,'type'=>'supplier',        'contact_name'=>'Operations Team',  'contact_email'=>'ops@jadawel.com.sa',        'country'=>'Saudi Arabia', 'account_manager_id'=>4,'status'=>'active', 'risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2023-03-01','qualification_expiry'=>'2024-03-01','overall_rating'=>3.5,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'DHL Express KSA',         'code'=>'VND005','category_id'=>4,'type'=>'supplier',        'contact_name'=>'Corporate Sales',  'contact_email'=>'corporate@dhl.com.sa',      'country'=>'Saudi Arabia', 'account_manager_id'=>4,'status'=>'approved','risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2023-01-01','qualification_expiry'=>'2025-01-01','overall_rating'=>4.0,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'Tahakom Digital',         'code'=>'VND006','category_id'=>5,'type'=>'service_provider','contact_name'=>'Ibrahim Al-Shehri','contact_email'=>'ibrahim@tahakom.com',       'country'=>'Saudi Arabia', 'account_manager_id'=>7,'status'=>'prospect','risk_level'=>'medium','qualification_status'=>'pending',  'qualification_date'=>null,         'qualification_expiry'=>null,         'overall_rating'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'Bupa Arabia',             'code'=>'VND007','category_id'=>6,'type'=>'service_provider','contact_name'=>'Corporate Team',   'contact_email'=>'corporate@bupa.com.sa',     'country'=>'Saudi Arabia', 'account_manager_id'=>3,'status'=>'approved','risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2024-06-01','qualification_expiry'=>'2026-06-01','overall_rating'=>4.1,'created_at'=>$now,'updated_at'=>$now],
            ['name'=>'Inaya Medical Clinics',   'code'=>'VND008','category_id'=>6,'type'=>'service_provider','contact_name'=>'Admin Office',     'contact_email'=>'admin@inaya.sa',            'country'=>'Saudi Arabia', 'account_manager_id'=>6,'status'=>'active', 'risk_level'=>'low',   'qualification_status'=>'qualified','qualification_date'=>'2024-02-01','qualification_expiry'=>'2026-02-01','overall_rating'=>3.9,'created_at'=>$now,'updated_at'=>$now],
        ]);

        DB::table('vendor_contracts')->insertOrIgnore([
            ['vendor_id'=>1,'contract_no'=>'CON-2024-001','title'=>'Oracle ERP Licensing & Support',      'type'=>'service',     'value'=>450000,'currency'=>'SAR','start_date'=>'2024-01-01','end_date'=>'2026-12-31','auto_renewal'=>1,'renewal_notice_days'=>90,'status'=>'active', 'owner_id'=>5,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>2,'contract_no'=>'CON-2024-002','title'=>'IT Infrastructure Managed Services', 'type'=>'service',     'value'=>280000,'currency'=>'SAR','start_date'=>'2024-03-01','end_date'=>'2025-02-28','auto_renewal'=>0,'renewal_notice_days'=>60,'status'=>'expired','owner_id'=>5,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>3,'contract_no'=>'CON-2024-003','title'=>'Annual Audit & Assurance Services',  'type'=>'service',     'value'=>120000,'currency'=>'SAR','start_date'=>'2024-01-01','end_date'=>'2024-12-31','auto_renewal'=>0,'renewal_notice_days'=>30,'status'=>'expired','owner_id'=>3,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>4,'contract_no'=>'CON-2024-004','title'=>'Facility Management & Cleaning',     'type'=>'maintenance', 'value'=>95000, 'currency'=>'SAR','start_date'=>'2024-01-01','end_date'=>'2025-12-31','auto_renewal'=>1,'renewal_notice_days'=>30,'status'=>'active', 'owner_id'=>4,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>5,'contract_no'=>'CON-2025-001','title'=>'Express Logistics Agreement',        'type'=>'service',     'value'=>65000, 'currency'=>'SAR','start_date'=>'2025-01-01','end_date'=>'2025-12-31','auto_renewal'=>1,'renewal_notice_days'=>30,'status'=>'active', 'owner_id'=>4,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>7,'contract_no'=>'CON-2025-002','title'=>'Group Health Insurance Policy',      'type'=>'service',     'value'=>380000,'currency'=>'SAR','start_date'=>'2025-06-01','end_date'=>'2026-05-31','auto_renewal'=>1,'renewal_notice_days'=>60,'status'=>'active', 'owner_id'=>3,'created_at'=>$now,'updated_at'=>$now],
            ['vendor_id'=>1,'contract_no'=>'CON-2026-001','title'=>'Oracle Cloud Infrastructure 2026',   'type'=>'service',     'value'=>520000,'currency'=>'SAR','start_date'=>'2026-01-01','end_date'=>'2026-12-31','auto_renewal'=>1,'renewal_notice_days'=>90,'status'=>'active', 'owner_id'=>5,'created_at'=>$now,'updated_at'=>$now],
        ]);
    }
}
